# Generated by Django 4.2.4 on 2023-08-30 12:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_article', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='rating_post',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='post',
            name='title_post',
            field=models.CharField(max_length=50, validators=[django.core.validators.MinValueValidator(3)]),
        ),
    ]
