# Generated by Django 4.2.4 on 2023-08-30 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_article', '0002_alter_post_rating_post_alter_post_title_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='rating_post',
            field=models.IntegerField(default=0),
        ),
    ]
