# Generated by Django 4.2.4 on 2023-08-30 13:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_article', '0004_alter_post_rating_post_alter_post_title_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='text_post',
            field=models.TextField(validators=[django.core.validators.MinLengthValidator(1)]),
        ),
    ]
