# Generated by Django 4.2.4 on 2023-08-31 13:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_article', '0005_alter_post_text_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='text_post',
            field=models.TextField(validators=[django.core.validators.MinLengthValidator(5)]),
        ),
        migrations.AlterField(
            model_name='post',
            name='title_post',
            field=models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(5)]),
        ),
    ]
