# Generated by Django 4.2.4 on 2023-09-08 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_article', '0010_remove_category_subscribers_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='email',
            field=models.EmailField(blank=True, max_length=50),
        ),
    ]
